name: myreddit

services:
  db:
    image: postgres:17
    container_name: myreddit-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.17.0
    container_name: myreddit-migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../database:/database
    command:
      [
        "-path=/database",
        "-database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable",
        "up"
      ]
  app:
    container_name: myreddit-app
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    environment:
      STORAGE_TYPE: ${STORAGE_TYPE}
      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}

      HTTP_PORT: ${HTTP_PORT}
      WS_KEEPALIVE_SECONDS: ${WS_KEEPALIVE_SECONDS}
    
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
